services:
  e-catalog-migas:
    container_name: e-catalog-migas
    image: e-catalog-migas:1.0
    # ports:
    # - "3300:3300"
    restart: unless-stopped
    env_file: .env

    networks:
      - private_net

networks:
  private_net:
    external: true
