services:
  e-catalog-migas:
    container_name: e-catalog-migas
    image: e-catalog-migas:latest
    ports:
      - "3310:80"
    restart: unless-stopped
    env_file: .env

    networks:
      - private_net

networks:
  private_net:
    external: true
